## 신경망 모델 구성하기

In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


In [3]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [4]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [13]:
pred_probab.argmax(1)

tensor([5], device='cuda:0')

In [14]:
pred_probab

tensor([[0.0921, 0.0983, 0.0875, 0.1074, 0.1080, 0.1088, 0.0992, 0.1019, 0.1042,
         0.0926]], device='cuda:0', grad_fn=<SoftmaxBackward0>)

In [11]:
X = torch.rand(1, 28, 28, device=device)
print(f'\t [ X.shape ] {X.shape}')
logits = model(X)
print(f'\t [ logits.shape ] {logits.shape}')
pred_probab = nn.Softmax(dim=1)(logits)
print(f'\t [ pred_prbob.shape ] {pred_probab.shape}' )
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

	 [ X.shape ] torch.Size([1, 28, 28])
	 [ logits.shape ] torch.Size([1, 10])
	 [ pred_prbob.shape] torch.Size([1, 10])
Predicted class: tensor([5], device='cuda:0')


### 모델 계층

In [15]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [16]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

torch.Size([3, 784])


In [17]:
layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

torch.Size([3, 20])


In [18]:
print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

Before ReLU: tensor([[-0.0112,  0.0479, -0.1383,  0.2831, -0.6548, -0.1220,  0.6486, -0.5407,
          0.4081, -0.1974, -0.4552,  0.5990,  0.1773,  0.6883, -0.9215,  0.7965,
          0.6805, -0.0388,  0.0974,  0.6106],
        [ 0.0946, -0.1023,  0.0078,  0.1383, -0.1650, -0.2439,  0.5220, -0.3834,
          0.3424, -0.0645, -0.2624,  0.3676,  0.3626,  0.6301, -0.8004,  0.5285,
          0.3032, -0.2917,  0.0442,  0.4394],
        [ 0.1518, -0.0900, -0.0253,  0.2431, -0.0849, -0.3135,  0.2110, -0.3708,
          0.0826, -0.1057, -0.4813, -0.1248,  0.4269,  0.9126, -0.8500,  0.5833,
          0.5046, -0.1595, -0.0630,  0.5528]], grad_fn=<AddmmBackward0>)


After ReLU: tensor([[0.0000, 0.0479, 0.0000, 0.2831, 0.0000, 0.0000, 0.6486, 0.0000, 0.4081,
         0.0000, 0.0000, 0.5990, 0.1773, 0.6883, 0.0000, 0.7965, 0.6805, 0.0000,
         0.0974, 0.6106],
        [0.0946, 0.0000, 0.0078, 0.1383, 0.0000, 0.0000, 0.5220, 0.0000, 0.3424,
         0.0000, 0.0000, 0.3676, 0.3626, 0.6301, 0.00

In [19]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)

In [20]:
softmax = nn.Softmax(dim=1)
pred_probab = softmax(logits)

In [23]:
print(pred_probab)

tensor([[0.0880, 0.1183, 0.1173, 0.0778, 0.1072, 0.1174, 0.0743, 0.1086, 0.0864,
         0.1046],
        [0.0868, 0.1187, 0.1086, 0.0751, 0.1056, 0.1221, 0.0770, 0.1117, 0.0889,
         0.1056],
        [0.0860, 0.1225, 0.1177, 0.0786, 0.1083, 0.1183, 0.0788, 0.1052, 0.0730,
         0.1117]], grad_fn=<SoftmaxBackward0>)


In [22]:
print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Model structure: NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[-0.0102,  0.0131, -0.0334,  ...,  0.0155, -0.0145, -0.0323],
        [-0.0296,  0.0291, -0.0174,  ..., -0.0334,  0.0163, -0.0330]],
       device='cuda:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.0.bias | Size: torch.Size([512]) | Values : tensor([-0.0067, -0.0262], device='cuda:0', grad_fn=<SliceBackward0>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[-0.0235,  0.0134,  0.0047,  ..., -0.0223, -0.0403, -0.0424],
        [-0.0361,  0.0276,  0.0045,  ..., -0.0206,  0.0065,  0.0226]],
       device='cuda:0', grad_fn=<Sl